-- Menu-first loop 2026-10-01 — ingredient price table for BM + Taller.
-- Every row starts PROVISIONAL (needs_confirm) at a Spanish wholesale norm,
-- ex-VAT, Ibiza. Rows with a purchase_pattern are overwritten by
-- fn_refresh_purchase_prices() from the venue's own invoice lines (unit
-- contract enforced) and become source='purchase'. Taller rows carry the same
-- patterns: its albaranes land as IFL and will take over as they arrive.
-- (name, aliases, unit, €/unit, kg per piece, purchase pattern, pack qty, pack unit)
begin;
create temp table pplan (name text, aliases text[], unit text, price numeric, uw numeric, pat text, pq numeric, pu text) on commit drop;
insert into pplan values
-- flours · bakery · dry
('''00'' pizza flour', '{"00 pizza flour","harina 00","pizza flour","harina caputo","tipo 00 flour"}', 'kg', 1.25, null, 'HARINA CAPUTO AZUL 25 KG%', 25, 'kg'),
('strong white bread flour', '{"bread flour","flour","harina","harina de fuerza","wheat flour","high-gluten bread flour"}', 'kg', 1.10, null, null, null, null),
('semolina', '{"semola rimacinata","bronze-extruded pasta flour"}', 'kg', 2.30, null, 'SEMOLA RIMACINATA CAPUTO 1 KG%', 1, 'kg'),
('bronze-extruded pasta', '{"homemade pasta","rigatoni","bronze-extruded rigatoni","pasta"}', 'kg', 3.20, null, null, null, null),
('breadcrumbs', '{"panko","pan rallado"}', 'kg', 2.40, null, null, null, null),
('sugar', '{"azucar","white sugar","caster sugar"}', 'kg', 1.05, null, null, null, null),
('icing sugar', '{"azucar glas"}', 'kg', 1.90, null, null, null, null),
('piloncillo', '{"panela"}', 'kg', 4.50, null, null, null, null),
('honey', '{"miel"}', 'kg', 9.00, null, null, null, null),
('maple syrup', '{"sirope de arce"}', 'l', 14.00, null, null, null, null),
('jam', '{"mermelada","marmalade","tomato jam","red fruit compote"}', 'kg', 5.50, null, null, null, null),
('granola', '{}', 'kg', 7.50, null, null, null, null),
('biscuit base', '{"galleta","digestive"}', 'kg', 4.80, null, null, null, null),
('fresh yeast', '{"levadura fresca","yeast","levadura"}', 'kg', 3.20, null, null, null, null),
('bicarbonate', '{"bicarbonato","baking soda"}', 'kg', 2.50, null, null, null, null),
('mature levain', '{"sourdough starter","levain","stiff mature levain","active sourdough starter","masa madre"}', 'kg', 1.00, null, null, null, null),
('salt', '{"sal","fine sea salt","fine salt","flaky sea salt","sea salt"}', 'kg', 0.60, null, null, null, null),
('rye bread', '{"pan de centeno"}', 'kg', 6.00, null, null, null, null),
('sourdough bread', '{"pan rustico","pan de masa madre","rustic bread","bread","house bread","toast"}', 'kg', 5.50, null, null, null, null),
('toast bread', '{"pan de molde"}', 'kg', 4.50, null, null, null, null),
('croissant (frozen, 70 g)', '{"croissant","croissant tradition"}', 'pcs', 0.59, 0.07, 'CROISSANT TRADITION%', null, null),
('pain au chocolat (frozen)', '{"pain au chocolat","napolitana"}', 'pcs', 0.72, 0.08, null, null, null),
('tomato cracker', '{}', 'pcs', 0.25, null, null, null, null),
-- dairy · eggs
('mozzarella', '{"mozzarella fior di latte","mozzarella julienne","fior di latte"}', 'kg', 6.90, null, 'MOZZARELLA JULIENNE DIANO%', 3, 'kg'),
('buffalo mozzarella', '{"bufala","mozzarella di bufala","bocconcini","bufala mozzarella","mozzarella de bufala"}', 'kg', 15.60, null, 'BOCCONCINI BUFALA 125 GR%', null, null),
('ricotta', '{"requeson","ricotta cheese"}', 'kg', 5.80, null, 'RICOTTA REQUESON%', 1, 'kg'),
('cream cheese', '{"queso crema","philadelphia"}', 'kg', 7.20, null, null, null, null),
('manchego', '{"queso manchego","manchego cheese"}', 'kg', 16.00, null, null, null, null),
('parmesan', '{"parmigiano","parmesano","parmigiano reggiano","grated parmesan"}', 'kg', 17.50, null, null, null, null),
('greek yogurt', '{"yogur griego","yogurt","yogur","natural yogurt"}', 'kg', 3.80, null, null, null, null),
('butter', '{"mantequilla","unsalted butter","herb butter","mantequilla de hierbas"}', 'kg', 8.50, null, null, null, null),
('cream', '{"nata","double cream","whipping cream","nata 35%"}', 'l', 4.20, null, null, null, null),
('milk', '{"leche","whole milk","tazas leche","leche entera"}', 'l', 1.58, null, 'LECHE ECOLOGICA PULEVA ENTER%1%', 1, 'l'),
('eggs', '{"egg","huevo","huevos","egg yolk","egg yolks","yema","claras","egg white"}', 'pcs', 0.22, 0.06, null, null, null),
('ice cream', '{"helado","gelato"}', 'kg', 7.00, null, null, null, null),
-- cured · charcuterie · meat · poultry
('Iberian ham', '{"jamon iberico","iberico","iberian ham","jamon"}', 'kg', 48.00, null, null, null, null),
('cooked ham', '{"jamon cocido","prosciutto cotto","york ham"}', 'kg', 8.90, null, 'JAMON COCIDO ARTESANO%', 1, 'kg'),
('sobrasada', '{"sobrassada","sobrasada payesa"}', 'kg', 14.00, null, null, null, null),
('rib eye', '{"entrecot","entrecotte","chuleton","galician beef rib eye","rib eye 350 g","beef rib eye"}', 'kg', 35.00, null, 'ENTRECOTTE BUEY%', 1, 'kg'),
('Galician blond beef', '{"vaca rubia gallega","rubia gallega","beef"}', 'kg', 38.00, null, null, null, null),
('chicken breast', '{"pollo","chicken","pechuga de pollo","free-range chicken","terra viva free-range chicken"}', 'kg', 9.50, null, null, null, null),
('chicken liver', '{"higado de pollo","chicken livers"}', 'kg', 4.50, null, null, null, null),
('chicken ragù', '{"ragu de pollo","pollonese","ragu"}', 'kg', 7.50, null, null, null, null),
-- fish · seafood
('sea bass', '{"lubina","dorada","sea bream","lubina o dorada","locally caught sea bass or bream"}', 'kg', 13.25, null, 'LUBINA 400/600%', 1, 'kg'),
('tuna', '{"atun","tuna loin","yellowfin tuna","atun rojo"}', 'kg', 24.00, null, null, null, null),
('monkfish', '{"rape","cola de rape","monkfish tail"}', 'kg', 25.85, null, 'COLA RAPE%', 1, 'kg'),
('skate', '{"raya","skate wing"}', 'kg', 12.00, null, null, null, null),
('red prawn', '{"gamba roja","carabinero","gamba roja de ibiza"}', 'kg', 85.00, 0.04, 'GAMBA ROJA%', 1, 'kg'),
('small prawns', '{"gambusin","gambas","camarones","prawns"}', 'kg', 18.00, null, null, null, null),
('oyster', '{"ostra","ostras","gillardeau","oysters"}', 'pcs', 1.98, null, 'GILLARDEAU N3/24%', 24, 'pcs'),
('sardine', '{"sardina","sardinas","sardines"}', 'kg', 7.50, 0.04, null, null, null),
('boquerones en vinagre', '{"boquerones","anchovies","pickled anchovies","boq. al vinagre"}', 'kg', 11.00, null, null, null, null),
-- vegetables · fruit · herbs
('tomato', '{"tomate","tomatoes","local organic tomatoes","tomato slices","tomate ensalada"}', 'kg', 3.20, null, 'TOMATE CANARIO%', 1, 'kg'),
('cherry tomato', '{"tomate cherry","cherry tomatoes"}', 'kg', 5.50, null, null, null, null),
('tomato sauce', '{"salsa de tomate","san marzano","tomate pera","pizza sauce","tomato passata","tomate triturado"}', 'kg', 1.65, null, 'TOMATE PERA REGINA LATA%', 3, 'kg'),
('tomato juice', '{"zumo de tomate"}', 'l', 1.80, null, null, null, null),
('tomato consommé', '{"consome de tomate","tomato water"}', 'l', 6.00, null, null, null, null),
('aubergine', '{"berenjena","berenjena negra","black aubergine","eggplant"}', 'kg', 2.19, null, 'Berenjena Negra%', 1, 'kg'),
('japanese aubergine', '{"berenjena japonesa"}', 'kg', 2.10, null, 'Berenjena Japonesa%', 1, 'kg'),
('courgette', '{"calabacin","zucchini","green courgette"}', 'kg', 3.05, null, 'Calabacin Verde%', 1, 'kg'),
('red pepper', '{"pimiento rojo","pimiento lamuyo rojo","red peppers","peppers"}', 'kg', 2.60, null, 'Pimiento Lamuyo Rojo%', 1, 'kg'),
('potatoes', '{"patata","patatas","potato","agria potato","organic potatoes"}', 'kg', 3.10, null, 'Patata Agria%', 1, 'kg'),
('potato millefeuille', '{"milhojas de patata"}', 'kg', 6.00, null, null, null, null),
('carrot', '{"zanahoria","carrots"}', 'kg', 1.90, null, 'ZANAHORIA%', 1, 'kg'),
('celery', '{"apio"}', 'kg', 2.50, null, 'APIO%', 1, 'kg'),
('cucumber', '{"pepino"}', 'kg', 2.50, null, null, null, null),
('kale', '{"kale toscano","cavolo nero","col rizada"}', 'kg', 6.15, null, 'KALE TOSCANO%', 1, 'kg'),
('spinach', '{"espinaca","espinacas"}', 'kg', 4.50, null, null, null, null),
('rocket', '{"rucula","arugula","rúcula"}', 'kg', 17.62, null, 'R_cula%Rocket%', 1, 'kg'),
('mesclun', '{"mezclum","mixed salad","salad","mesclun juntos farm","mixed leaves"}', 'kg', 25.00, null, 'Mezclum%', 1, 'kg'),
('crudités', '{"crudites","raw vegetables","organic vegetables","garnish of the day","garnish","vegetables","topping of the day","seasonal vegetables"}', 'kg', 4.00, null, null, null, null),
('ferments', '{"kimchi","fermentos","pickles"}', 'kg', 9.00, null, null, null, null),
('pickled onion', '{"cebolla encurtida","onion","cebolla","pickled onions","red onion","shallot","chalota"}', 'kg', 1.80, null, 'Cebolla Seca Roja%', 1, 'kg'),
('garlic', '{"ajo","garlic clove"}', 'kg', 7.10, 0.005, 'AJO SECO%', 0.25, 'kg'),
('avocado', '{"aguacate","aguacate hass","avocados"}', 'kg', 6.43, 0.2, 'AGUACATE HASS%', 1, 'kg'),
('melon', '{"melon","piel de sapo","galia melon"}', 'kg', 1.95, null, 'Mel_n Piel de Sapo%', 1, 'kg'),
('fresh fruit', '{"fruit","fruta","seasonal fruit","fruits","frutas","mixed fruit"}', 'kg', 3.50, null, null, null, null),
('banana', '{"platano","bananas"}', 'kg', 0.97, 0.15, 'BANANA%', 1, 'kg'),
('pineapple', '{"piña","pina","pineapple peel"}', 'kg', 2.20, null, null, null, null),
('strawberries', '{"fresa","fresas","strawberry","saffron-marinated strawberries"}', 'kg', 4.69, null, 'FRESAS CONGELADAS%', 1, 'kg'),
('figs', '{"higos","fig"}', 'kg', 7.00, null, null, null, null),
('açaí', '{"acai","acai pulp"}', 'kg', 12.00, null, null, null, null),
('lemon', '{"limon","limones","lemons","lemon leaf","hoja de limon"}', 'pcs', 0.35, 0.12, null, null, null),
('lemon juice', '{"jugo de limon","zumo de limon"}', 'l', 4.00, null, null, null, null),
('lime', '{"lima","limes","fresh lime"}', 'pcs', 0.45, 0.08, null, null, null),
('lime juice', '{"zumo de lima"}', 'l', 9.00, null, null, null, null),
('orange', '{"naranja","oranges","orange, half-wheel","orange peel","citrus peel"}', 'pcs', 0.30, 0.2, null, null, null),
('orange juice', '{"zumo de naranja","fresh orange juice"}', 'l', 2.50, null, null, null, null),
('peach juice', '{"zumo de melocoton","peach puree"}', 'l', 2.50, null, null, null, null),
('basil', '{"albahaca","fresh basil"}', 'kg', 10.00, null, 'Albahaca / Basil%', 0.1, 'kg'),
('mint', '{"menta","hierbabuena","fresh mint"}', 'kg', 12.00, null, null, null, null),
('rosemary', '{"romero"}', 'kg', 9.00, null, null, null, null),
('oregano', '{"dried oregano"}', 'kg', 14.00, null, null, null, null),
('herbs', '{"hierbas","fresh herbs","mixed herbs","Ibizan herbs","hierbas ibicencas","parsley","perejil"}', 'kg', 10.00, null, null, null, null),
('shiso', '{}', 'kg', 60.00, null, null, null, null),
('lemongrass', '{"hierba limon","citronela"}', 'kg', 9.00, null, null, null, null),
('ginger', '{"jengibre"}', 'kg', 3.24, null, 'JENGIBRE%', 1, 'kg'),
('chilli', '{"chili","guindilla","chilli flakes","chili flakes","red chilli"}', 'kg', 9.00, null, null, null, null),
('cinnamon', '{"canela"}', 'kg', 12.00, null, null, null, null),
('spices', '{"especias","sweet spices","especias dulces","mixed spices"}', 'kg', 20.00, null, null, null, null),
('saffron', '{"azafran"}', 'kg', 4500.00, null, null, null, null),
('black truffle', '{"trufa","truffle","trufa negra"}', 'kg', 900.00, null, null, null, null),
('edible flowers', '{"flores comestibles","flowers","dried flowers","flores secas"}', 'kg', 150.00, null, null, null, null),
('pollen', '{"polen","bee pollen"}', 'kg', 35.00, null, null, null, null),
('olives', '{"aceitunas","olivas"}', 'kg', 4.20, null, null, null, null),
('capers', '{"alcaparras"}', 'kg', 6.20, null, 'ALCAPARRAS GUEROLA%', 1.5, 'kg'),
('mushroom risotto', '{"risotto de setas","risotto"}', 'kg', 6.50, null, null, null, null),
('vegetable caponata', '{"caponata","caponata de verduras"}', 'kg', 5.50, null, null, null, null),
('miso', '{"shiro miso","white miso","miso paste"}', 'kg', 6.50, null, 'SHIRO MISO%', 1, 'kg'),
('sesame', '{"sesamo","sesame seeds","sésamo"}', 'kg', 6.00, null, null, null, null),
('mirin', '{}', 'l', 7.50, null, null, null, null),
('mustard', '{"mostaza","italian mustard"}', 'kg', 6.00, null, null, null, null),
('kombucha', '{}', 'l', 4.50, null, null, null, null),
('sexy pomegranate tea blend', '{"sexy pomegranate","pomegranate tea"}', 'kg', 55.00, null, 'SEXY POMEGRANATE%', 1, 'kg'),
('water', '{"agua"}', 'l', 0.00, null, null, null, null),
-- oils · vinegars · sauces · preps
('extra virgin olive oil', '{"aove","extra-virgin olive oil","olive oil","evoo","aceite de oliva","aceite de oliva virgen extra","garlic oil","aceite de ajo","garlic parsley oil","green oil","aceite verde","lemon oil","aceite de limon"}', 'l', 5.09, null, 'ACEITE VIRG.EXTRA ABRIL%', 5, 'l'),
('frying oil', '{"aceite de girasol","sunflower oil","neutral oil","aceite risso"}', 'l', 3.00, null, 'RISSO ACEITE E-FREE 10L%', 10, 'l'),
('sherry vinegar', '{"vinagre de jerez","vinegar","vinagre"}', 'l', 6.50, null, null, null, null),
('chardonnay vinaigrette', '{"vinagreta","vinaigrette","vinagreta de chardonnay"}', 'l', 8.00, null, null, null, null),
('alioli', '{"aioli","alioli de ajo negro"}', 'kg', 5.00, null, null, null, null),
('truffle mayo', '{"mayonesa de trufa","truffle mayonnaise"}', 'kg', 9.50, null, null, null, null),
('sherry reduction', '{"reduccion de jerez","demi-glace","demi glace"}', 'l', 18.00, null, null, null, null),
('monkfish sauce', '{"its sauce","su salsa","fish sauce base"}', 'l', 9.00, null, null, null, null),
('prawn emulsion', '{"emulsion de gamba"}', 'kg', 14.00, null, null, null, null),
('prawn oil', '{"aceite de gamba"}', 'l', 16.00, null, null, null, null),
('oyster foam', '{"espuma de ostra"}', 'kg', 15.00, null, null, null, null),
('sobrasada sauce', '{"salsa de sobrasada","sobrasada butter"}', 'kg', 12.00, null, null, null, null),
('saffron béchamel', '{"bechamel de azafran","bechamel"}', 'kg', 4.50, null, null, null, null),
('lemon sorbet', '{"sorbete de limon"}', 'kg', 6.00, null, null, null, null),
('strawberry sorbet', '{"sorbete de fresa"}', 'kg', 6.50, null, null, null, null),
('yogurt mousse', '{"mousse de yogur"}', 'kg', 5.50, null, null, null, null),
-- bar
('Aperol', '{"aperol"}', 'l', 10.56, null, 'APEROL BOTELLA%', 1, 'l'),
('Campari', '{"campari"}', 'l', 14.00, null, null, null, null),
('vermouth rosso', '{"vermut rojo","vermouth","vermut"}', 'l', 8.00, null, null, null, null),
('gin', '{"ginebra"}', 'l', 13.25, null, 'GINEBRA BOMBAY%', 0.7, 'l'),
('vodka', '{}', 'l', 12.00, null, null, null, null),
('white rum', '{"ron blanco","rum","ron"}', 'l', 12.50, null, null, null, null),
('cachaça', '{"cachaca"}', 'l', 11.00, null, 'CACHACA%', 1, 'l'),
('mezcal', '{}', 'l', 32.00, null, null, null, null),
('tequila blanco', '{"tequila"}', 'l', 20.00, null, null, null, null),
('brandy', '{"coñac","cognac"}', 'l', 11.00, null, null, null, null),
('anise liqueur', '{"anis","hierbas ibicencas base","anise"}', 'l', 9.00, null, null, null, null),
('neutral alcohol 96', '{"alcohol","alcohol 96"}', 'l', 14.00, null, null, null, null),
('spirit', '{"house spirit","destilado","licor"}', 'l', 13.00, null, null, null, null),
('premium spirit', '{}', 'l', 28.00, null, null, null, null),
('cava', '{"prosecco","sparkling wine","espumoso"}', 'l', 7.50, null, null, null, null),
('soda water', '{"soda","agua con gas","sparkling water"}', 'l', 0.80, null, null, null, null),
('ginger beer', '{}', 'l', 3.20, null, null, null, null),
('mixer', '{"tonica","tonic","cola","refresco"}', 'l', 1.60, null, null, null, null);

insert into ingredient_prices (entity_id, canonical_name, aliases, unit, price_eur, unit_weight_kg, source, needs_confirm, purchase_pattern, pack_qty, pack_unit, estimated_by, note)
select e.id, p.name, p.aliases, p.unit, p.price, p.uw, 'provisional', true, p.pat, p.pq, p.pu, 'menu-first-builder (Claude), Spanish wholesale norm 2026-10-01',
       'estimate — ex-VAT Ibiza wholesale; confirm or correct'
from pplan p cross join (select id from entities where slug in ('bm','taller')) e
on conflict (entity_id, name_norm) do update set aliases = excluded.aliases, purchase_pattern = excluded.purchase_pattern, pack_qty = excluded.pack_qty, pack_unit = excluded.pack_unit, unit_weight_kg = excluded.unit_weight_kg;
commit;
